vagrant_hostname: local.stanleycup2019.com
vagrant_machine_name: stanleycup2019
vagrant_ip: 192.168.196.172
vagrant_box: geerlingguy/ubuntu1604
workspace: /root
drupal_site_name: 'BLTed 10'
vagrant_synced_folders:
    -
        local_path: .
        destination: /var/www/stanleycup2019
        type: nfs
drupal_build_composer_project: false
drupal_composer_path: false
drupal_composer_install_dir: /var/www/stanleycup2019
drupal_core_path: /var/www/stanleycup2019/docroot
ssh_home: /var/www/stanleycup2019
apache_vhosts:
    -
        servername: '{{ drupal_domain }}'
        serveralias: 'www.{{ drupal_domain }}'
        documentroot: '{{ drupal_core_path }}'
        extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
    -
        servername: 'dashboard.{{ drupal_domain }}'
        serveralias: 'www.dashboard.{{ drupal_domain }}'
        documentroot: /var/www/dashboard
        extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
    -
        servername: 'adminer.{{ vagrant_hostname }}'
        documentroot: '{{ adminer_install_dir }}'
        extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
    -
        servername: 'xhprof.{{ vagrant_hostname }}'
        documentroot: '{{ php_xhprof_html_dir }}'
        extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
    -
        servername: 'pimpmylog.{{ vagrant_hostname }}'
        documentroot: '{{ pimpmylog_install_dir }}'
        extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
    -
        servername: local.site2.com
        documentroot: '{{ drupal_core_path }}'
        extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
mysql_databases:
    -
        name: drupal
        encoding: utf8
        collation: utf8_general_ci
    -
        name: site2
        encoding: utf8
        collation: utf8_general_ci
mysql_users:
    -
        name: drupal
        host: '%'
        password: drupal
        priv: 'drupal%.*:ALL'
    -
        name: site2
        host: '%'
        password: site2
        priv: 'site2%.*:ALL'
drupal_install_site: false
configure_drush_aliases: false
extra_packages:
    - patchutils
    - sqlite
installed_extras:
    - adminer
    - selenium
    - drush
    - mailhog
    - memcached
    - nodejs
    - solr
    - xdebug
php_version: '7.2'
php_packages_extra:
    - 'php{{ php_version }}-bz2'
    - 'php{{ php_version }}-imagick'
    - imagemagick
php_xdebug_version: 2.7.1
php_xdebug_default_enable: 0
php_xdebug_cli_disable: 'yes'
php_xdebug_remote_port: '9000'
php_memory_limit: 512M
solr_version: 4.5.1
post_provision_scripts:
    - ../../../acquia/blt/scripts/drupal-vm/configure-solr.sh
    - ../../../acquia/blt/scripts/drupal-vm/post-provision.php
